stages:
  - setup
  - test
  - app-test
  - cleanup
gcp-cluster:
  image: atulabhi/kops:v8
  stage: setup
  script: 
    - chmod u+x ./script/gcp
    - ./script/gcp
  artifacts:
    paths:
      - .kube/

openebs_gcp_deploy:
  image: atulabhi/kops:v8
  stage: test
  dependencies:
    - gcp-cluster
  script:
    - echo "Deploying-Openebs"
    - ls -a
    - pwd
    - mkdir ~/.kube-openebs
    - cp  .kube/config ~/.kube-openebs/config
    - kubectl config get-contexts
    - wget https://raw.githubusercontent.com/ashishranjan738/testlit/master/setup_openebs.yaml
    - kubectl apply -f setup_openebs.yaml
  artifacts:
    paths:
      - .kube-openebs/

apps-gcp-deploy:
  stage: app-test
  script:
   - echo "app-deploy"
   - kubectl apply -f https://raw.githubusercontent.com/shashank855/litmus/percona_test/apps/percona/deployers/deploy_percona_litmus.yaml
  
  dependencies:
    - openebs_gcp_deploy
     
cleanup-gcp:
  image: atulabhi/kops:v8
  dependencies:
    - gcp-cluster
  stage: cleanup
  script: 
    - chmod u+x ./script/gcp-cleanup
    - ./script/gcp-cleanup
  when: always
