stages:
  - cluster-setup
  - infra-setup
  - stateful-apps-deploy
  - apps-loadgen  
  - chaos-test
  - cleanup
gcp-cluster:
  image: atulabhi/kops:v8
  stage: cluster-setup
  script: 
    - chmod 775 ./script/gcp
    - ./script/gcp
  artifacts:
    when: always
    paths:
      - .kube/

openebs_gcp_deploy:
  image: atulabhi/kops:v8
  stage: infra-setup
  dependencies:
    - gcp-cluster
  script:
    - echo "Setting up infrastructure"
    - chmod 775 ./script/infra-setup
    - ./script/infra-setup
  artifacts:
    paths:
      - .kube-openebs/

percona 0:
  stage: stateful-apps-deploy
  image: atulabhi/kops:v8
  script:
    - chmod 775 ./script/percona-app-deploy
    - ./script/percona-app-deploy
  dependencies:
    - openebs_gcp_deploy

percona 1:
  image: atulabhi/kops:v8
  stage: apps-loadgen
  script: 
   - echo "jobs-Gcp-Started"
   - chmod 775 ./script/percona-loadgen
   - ./script/percona-loadgen
  dependencies:
   - openebs_gcp_deploy  

cleanup-gcp:
  image: atulabhi/kops:v8
  dependencies:
    - gcp-cluster
  stage: cleanup
  script: 
    - chmod 775 ./script/gcp-cleanup
    - ./script/gcp-cleanup
  when: always
