stages:
  - cluster-setup
  - infra-setup
  - stateful-apps-deploy
  - chaos-test
  - cleanup
  - deploy
gcp-cluster:
  image: atulabhi/kops:v8
  stage: cluster-setup
  script: 
    - chmod 775 ./script/gcp
    - ./script/gcp
  artifacts:
    when: always
    paths:
      - .kube/

openebs_gcp_deploy:
  image: atulabhi/kops:v8
  stage: infra-setup
  dependencies:
    - gcp-cluster
  script:
    - echo "Setting up infrastructure"
    - chmod 775 ./script/infra-setup
    - ./script/infra-setup
  artifacts:
    paths:
      - .kube-openebs/

apps-gcp-deploy:
  stage: stateful-apps-deploy
  script:
    - chmod 775 ./script/stateful-app-deploy
    - ./script/stateful-app-deploy
  dependencies:
    - openebs_gcp_deploy
     
cleanup-gcp:
  image: atulabhi/kops:v8
  dependencies:
    - gcp-cluster
  stage: cleanup
  script: 
    - chmod 775 ./script/gcp-cleanup
    - ./script/gcp-cleanup
  when: always

deploy:
  stage: deploy
  script:
   - echo "deploy to production"
