stages:
  - cluster-setup
  - infra-setup
  - stateful-apps-deploy
  - chaos-test
  - cleanup
gcp-cluster:
  image: atulabhi/kops:v8
  stage: cluster-setup
  script: 
    - chmod 775 ./script/gcp
    - ./script/gcp
  artifacts:
    when: always
    paths:
      - .kube/

openebs_gcp_deploy:
  image: atulabhi/kops:v8
  stage: infra-setup
  dependencies:
    - gcp-cluster
  script:
    - echo "Setting up infrastructure"
    - chmod 775 ./script/infra-setup
    - ./script/infra-setup
  artifacts:
    paths:
      - .kube-openebs/

apps-gcp-deploy:
  stage: stateful-apps-deploy
  image: atulabhi/kops:v8
  script:
    - chmod 775 ./script/stateful-app-deploy
    - ./script/stateful-app-deploy
  dependencies:
    - openebs_gcp_deploy
     
Litmus-Chaos:
  stage: chaos-test
  image: atulabhi/kops:v8
  script:
   - echo " Introducing Chaos"
   - mkdir ~/.kube
   - cp  .kube/config ~/.kube/config 
   - kubectl create -f https://raw.githubusercontent.com/atulabhi/litmus/v0.7-RC1/apps/percona/chaos/openebs_volume_replica_failure/run_litmus_test.yaml
   - chmod 755 ./script/chaos
   - ./script/chaos
  dependencies:
    - gcp-cluster

cleanup-gcp:
  image: atulabhi/kops:v8
  dependencies:
    - gcp-cluster
  stage: cleanup
  script: 
    - chmod 775 ./script/gcp-cleanup
    - ./script/gcp-cleanup
  when: always
